function[u] = residuals2(T, y, Z, spec, Theta)
u = reshape(reshape(flipud(rot90(y(spec.lags+1:T(1,1), :) )), (T(1,1)-spec.lags)*T(1,2), 1) - kron(Z, eye(T(1,2)))*Theta, ...
    T(1,2), T(1,1)-spec.lags)';